In [8]:
from PIL import Image
import numpy as np
import pandas as pd

In [9]:
x = np.array([[1,1,1], [2,2,2]])
y = np.array([[1,2,1], [1,2,1]])

x += y
print(x.mean())

2.8333333333333335


In [18]:
trainData = 'trainData.csv'
im_size = 128

data = pd.read_csv(trainData, header=None)
print(data)
N = len(data)

pixel_values = np.zeros((128,128))
# std = np.zeros((128,128))

for i in range(N):
    img = Image.open(data[0].iloc[i]).convert("L")
    im = np.asarray(img)
    if im.shape != (im_size, im_size):
        im = np.asarray(Image.fromarray(im).resize((im_size, im_size)))
    # print(im.shape)
    # print(data[0].iloc[i])
    pixel_values += im

means = pixel_values / N
std_sum = np.zeros((im_size, im_size))

for i in range(N):
    img = Image.open(data[0].iloc[i]).convert("L")
    im = np.asarray(img)
    if im.shape != (im_size, im_size):
        im = np.asarray(Image.fromarray(im).resize((im_size, im_size)))
    # print(im.shape)
    # print(data[0].iloc[i])
    std_sum += np.square(im - means)

std = np.sqrt(std_sum / N)

print(f'[INFO] Pixel mean is {means}')
print(f'[INFO] Pixel std is {std}')

                                                       0    1
0      /dcs/large/u2009169/seal-script-images/459/459...  459
1      /dcs/large/u2009169/seal-script-images/459/459...  459
2      /dcs/large/u2009169/seal-script-images/459/459...  459
3      /dcs/large/u2009169/seal-script-images/459/459...  459
4      /dcs/large/u2009169/seal-script-images/459/459...  459
...                                                  ...  ...
73137  /dcs/large/u2009169/seal-script-images/640/640...  640
73138  /dcs/large/u2009169/seal-script-images/640/640...  640
73139  /dcs/large/u2009169/seal-script-images/640/640...  640
73140  /dcs/large/u2009169/seal-script-images/640/640...  640
73141  /dcs/large/u2009169/seal-script-images/640/640...  640

[73142 rows x 2 columns]
[INFO] Pixel mean is [[217.42453037 217.37648683 217.3618851  ... 217.62162643 217.60699735
  217.49622652]
 [217.2666457  217.17721692 217.12131197 ... 217.44815564 217.45095841
  217.47372235]
 [217.05810615 216.97983375 216.983

In [23]:
print(means.astype('uint8'))
print(std.astype('uint8'))

Image.fromarray(means).save('mean_image.png', 'PNG')
Image.fromarray(std).save('std_image.png', 'PNG')

[[217 217 217 ... 217 217 217]
 [217 217 217 ... 217 217 217]
 [217 216 216 ... 217 217 217]
 ...
 [217 217 217 ... 217 217 217]
 [217 217 217 ... 217 217 217]
 [217 217 217 ... 217 217 217]]
[[45 45 44 ... 44 44 45]
 [45 45 45 ... 44 45 45]
 [45 45 45 ... 44 44 44]
 ...
 [44 44 44 ... 44 44 44]
 [44 44 44 ... 44 44 44]
 [45 45 44 ... 44 44 45]]


AttributeError: module 'PIL.Image' has no attribute 'save'